# Site
title:              WHO YOU WANT TO BE
bio:                'Jekyll version of the Massively theme by HTML5UP'
description:        "Jekyll version of the Massively theme by HTML5UP"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author: "aurore"

collections:
  csblog:
    output: true
    permalink: "/computer-science/:title/"
    layout: post_for_cs
    author: "aurore"

# Jekyll
permalink:          /computer-science/:title/
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   www-auroretech-com-1
sites_comments:     true

# Social
analytics-id:       "UA-120895017-1"
twitter:            MeiertaylorMaze
facebook:           default
instagram:          __sakura13
github:             auroretech

# personal
location:           China 
phone:              012456789
email:              mrzhangx0504@outlook.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
